In [148]:

import pandas as pd
import numpy as np


In [149]:
data=pd.DataFrame({
    "X1":[0,0,1,1,0,0,1,1],
    "X2":[0,1,0,1,0,1,0,1],
    "X3":[0,0,0,0,1,1,1,1],
    "Y":[0,1,1,0,1,0,0,1]
})
data

X1  X2  X3  Y
0   0   0   0  0
1   0   1   0  1
2   1   0   0  1
3   1   1   0  0
4   0   0   1  1
5   0   1   1  0
6   1   0   1  0
7   1   1   1  1

In [152]:
label=np.array(data['Y'])
x=np.array(data.drop('Y',axis=1))
x.reshape(-1,3)
x

array([[0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 1, 0],
       [0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [204]:
layers=[3,10,1]

def initialize_param(layers):
    parameters={}
    L=len(layers)
    for i in range(1,L):
        parameters['W'+str(i)]=np.random.randn(layers[i],layers[i-1])*0.01
        parameters['b'+str(i)]=np.zeros(layers[i])*0.01
    return parameters
par=initialize_param(layers)
par

{'W1': array([[-0.00498156, -0.00630277,  0.00695939],
        [-0.00832913,  0.01540625,  0.02157456],
        [-0.00693257,  0.00268032, -0.0044606 ],
        [-0.01436425, -0.00199639,  0.00607208],
        [ 0.01434643, -0.01392745, -0.0036258 ],
        [ 0.00258482,  0.01196963, -0.01236557],
        [-0.0057766 , -0.01267531, -0.01870018],
        [ 0.01275854, -0.00650516, -0.00097233],
        [-0.00620819,  0.00194088,  0.00243059],
        [ 0.00532135,  0.02287792, -0.00853155]]),
 'b1': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'W2': array([[-0.00874689, -0.00469092, -0.00340235, -0.00523874, -0.00660325,
          0.00586334,  0.00147022,  0.02077029, -0.00588101, -0.00077663]]),
 'b2': array([0.])}

In [205]:
def relu(x):
    x[x<0]=0
    return x
def sigm(x):
    x=(1/(1+np.exp(-x)))
    return x

In [223]:
def forward(x,param):
    a0=np.copy(x)
    
    z1=a0.dot(param['W1'].T)+param['b1']
    a1=relu(z1)
    
    z2=a1.dot(param['W2'].T)+param['b2']
    a2=sigm(z2)
    cache={"a0"=a0,'W1'=param['W1'],'b1'=param['b1'],"z1"=z1,"z2"=z2,"a1"=a1,'W2'=param['W2'],'b2'=param['b2']}
    return a2,cache
print(forward(x,par))

SyntaxError: invalid syntax (<ipython-input-223-d9ea0b50c894>, line 9)

In [222]:
def loss(a2,y):
    a2=a2.reshape(-1)
    y=y.reshape(-1)
    print(a2)
    logl=np.dot(y,np.log(a2).T)+np.dot((1-y),np.log(1-a2).T)
    loss=(-1/y.size)*logl
    return loss
a2,cache=forward(x,par)
loss(a,label)

[0.5        0.4999899  0.50004532 0.50003934 0.49994795 0.49994065
 0.50002364 0.49999321]


0.6931539927670884

In [147]:
import tensorflow as tf

from tensorflow.keras import layers

In [5]:
data=pd.DataFrame({
    "X1":[0,0,1,1,0,0,1,1],
    "X2":[0,1,0,1,0,1,0,1],
    "X3":[0,0,0,0,1,1,1,1],
    "Y":[0,1,1,0,1,0,0,1]
})
data

X1  X2  X3  Y
0   0   0   0  0
1   0   1   0  1
2   1   0   0  1
3   1   1   0  0
4   0   0   1  1
5   0   1   1  0
6   1   0   1  0
7   1   1   1  1

In [13]:
label=np.array(data['Y'])
x=np.array(data.drop('Y',axis=1))
x.reshape(-1,3)

array([[0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 1, 0],
       [0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [10]:
x,label

(array([[0, 0, 0],
        [0, 1, 0],
        [1, 0, 0],
        [1, 1, 0],
        [0, 0, 1],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 1]]),
 array([0, 1, 1, 0, 1, 0, 0, 1]))

In [142]:
def model():
    inputs=layers.Input(shape=(3))
    x=layers.Dense(10,activation="relu")(inputs)
    outputs=layers.Dense(2,activation='softmax')(x)
    model=tf.keras.Model(inputs=inputs,outputs=outputs)
    return model
my_mod=model()

In [143]:
my_mod.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
    metrics=['accuracy']
)

In [144]:
my_mod.fit(x,label,epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 168ms/step - loss: 0.6821 - accuracy: 0.8750
Epoch 2/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.6815 - accuracy: 0.7500
Epoch 3/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6808 - accuracy: 0.7500
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6800 - accuracy: 0.7500
Epoch 5/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6793 - accuracy: 0.7500
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6787 - accuracy: 0.7500
Epoch 7/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6780 - accuracy: 0.7500
Epoch 8/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6773 - accuracy: 0.7500
Epoch 9/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.6767 - accuracy: 0.7500
Epoch 10/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6760 - accuracy: 0.7500
Epoch 11/1000
1/1

1/1 [==============================] - 0s 2ms/step - loss: 0.6379 - accuracy: 0.7500
Epoch 84/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6368 - accuracy: 0.7500
Epoch 85/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6361 - accuracy: 0.7500
Epoch 86/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6371 - accuracy: 0.7500
Epoch 87/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6360 - accuracy: 0.7500
Epoch 88/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6350 - accuracy: 0.7500
Epoch 89/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6346 - accuracy: 0.7500
Epoch 90/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6352 - accuracy: 0.7500
Epoch 91/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.6342 - accuracy: 0.7500
Epoch 92/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6331 - accuracy: 0.7500
Epoch 93/1000
1/1 [=====

1/1 [==============================] - 0s 2ms/step - loss: 0.5990 - accuracy: 0.7500
Epoch 166/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5978 - accuracy: 0.7500
Epoch 167/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5984 - accuracy: 0.7500
Epoch 168/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5985 - accuracy: 0.7500
Epoch 169/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5974 - accuracy: 0.7500
Epoch 170/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5964 - accuracy: 0.7500
Epoch 171/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5956 - accuracy: 0.7500
Epoch 172/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5957 - accuracy: 0.7500
Epoch 173/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5961 - accuracy: 0.7500
Epoch 174/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5951 - accuracy: 0.8750
Epoch 175/1000


1/1 [==============================] - 0s 2ms/step - loss: 0.5563 - accuracy: 0.7500
Epoch 248/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5555 - accuracy: 0.8750
Epoch 249/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5549 - accuracy: 0.7500
Epoch 250/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5534 - accuracy: 0.7500
Epoch 251/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5534 - accuracy: 0.7500
Epoch 252/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5536 - accuracy: 0.7500
Epoch 253/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5528 - accuracy: 0.7500
Epoch 254/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5517 - accuracy: 0.7500
Epoch 255/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5511 - accuracy: 0.7500
Epoch 256/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5503 - accuracy: 0.7500
Epoch 257/1000


1/1 [==============================] - 0s 2ms/step - loss: 0.5032 - accuracy: 0.7500
Epoch 330/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5023 - accuracy: 0.7500
Epoch 331/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5012 - accuracy: 0.7500
Epoch 332/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5000 - accuracy: 0.7500
Epoch 333/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4987 - accuracy: 0.7500
Epoch 334/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4981 - accuracy: 0.7500
Epoch 335/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4974 - accuracy: 0.7500
Epoch 336/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4983 - accuracy: 0.7500
Epoch 337/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4978 - accuracy: 0.7500
Epoch 338/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4962 - accuracy: 0.7500
Epoch 339/1000


1/1 [==============================] - 0s 2ms/step - loss: 0.4501 - accuracy: 0.7500
Epoch 412/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4506 - accuracy: 0.7500
Epoch 413/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4494 - accuracy: 0.7500
Epoch 414/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4480 - accuracy: 0.7500
Epoch 415/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4491 - accuracy: 0.7500
Epoch 416/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4481 - accuracy: 0.7500
Epoch 417/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4461 - accuracy: 0.7500
Epoch 418/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4447 - accuracy: 0.7500
Epoch 419/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4455 - accuracy: 0.7500
Epoch 420/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4457 - accuracy: 0.7500
Epoch 421/1000


1/1 [==============================] - 0s 2ms/step - loss: 0.3974 - accuracy: 0.7500
Epoch 494/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3973 - accuracy: 0.7500
Epoch 495/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3959 - accuracy: 0.7500
Epoch 496/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3970 - accuracy: 0.7500
Epoch 497/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3968 - accuracy: 0.7500
Epoch 498/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3943 - accuracy: 0.7500
Epoch 499/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3932 - accuracy: 0.7500
Epoch 500/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3930 - accuracy: 0.7500
Epoch 501/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3944 - accuracy: 0.7500
Epoch 502/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3932 - accuracy: 0.7500
Epoch 503/1000


1/1 [==============================] - 0s 2ms/step - loss: 0.3442 - accuracy: 1.0000
Epoch 576/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3429 - accuracy: 1.0000
Epoch 577/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3431 - accuracy: 0.8750
Epoch 578/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3433 - accuracy: 1.0000
Epoch 579/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3425 - accuracy: 1.0000
Epoch 580/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3413 - accuracy: 1.0000
Epoch 581/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3411 - accuracy: 1.0000
Epoch 582/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3392 - accuracy: 1.0000
Epoch 583/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3379 - accuracy: 1.0000
Epoch 584/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3388 - accuracy: 0.8750
Epoch 585/1000


1/1 [==============================] - 0s 3ms/step - loss: 0.2932 - accuracy: 1.0000
Epoch 657/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2928 - accuracy: 1.0000
Epoch 658/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2903 - accuracy: 1.0000
Epoch 659/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2889 - accuracy: 1.0000
Epoch 660/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2899 - accuracy: 1.0000
Epoch 661/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2899 - accuracy: 1.0000
Epoch 662/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2885 - accuracy: 1.0000
Epoch 663/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2878 - accuracy: 1.0000
Epoch 664/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2878 - accuracy: 1.0000
Epoch 665/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2859 - accuracy: 1.0000
Epoch 666/1000


1/1 [==============================] - 0s 2ms/step - loss: 0.2433 - accuracy: 1.0000
Epoch 739/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2415 - accuracy: 1.0000
Epoch 740/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2429 - accuracy: 1.0000
Epoch 741/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2423 - accuracy: 1.0000
Epoch 742/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2402 - accuracy: 1.0000
Epoch 743/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2412 - accuracy: 1.0000
Epoch 744/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2419 - accuracy: 1.0000
Epoch 745/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2396 - accuracy: 1.0000
Epoch 746/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2385 - accuracy: 1.0000
Epoch 747/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2391 - accuracy: 1.0000
Epoch 748/1000


Epoch 820/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2016 - accuracy: 1.0000
Epoch 821/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2012 - accuracy: 1.0000
Epoch 822/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1994 - accuracy: 1.0000
Epoch 823/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1987 - accuracy: 1.0000
Epoch 824/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1984 - accuracy: 1.0000
Epoch 825/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2004 - accuracy: 1.0000
Epoch 826/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1988 - accuracy: 1.0000
Epoch 827/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1980 - accuracy: 1.0000
Epoch 828/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1974 - accuracy: 1.0000
Epoch 829/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1959 - accuracy: 1.0000


1/1 [==============================] - 0s 2ms/step - loss: 0.1649 - accuracy: 1.0000
Epoch 902/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1650 - accuracy: 1.0000
Epoch 903/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1649 - accuracy: 1.0000
Epoch 904/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1642 - accuracy: 1.0000
Epoch 905/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1661 - accuracy: 1.0000
Epoch 906/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1646 - accuracy: 1.0000
Epoch 907/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1634 - accuracy: 1.0000
Epoch 908/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1633 - accuracy: 1.0000
Epoch 909/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1621 - accuracy: 1.0000
Epoch 910/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1615 - accuracy: 1.0000
Epoch 911/1000


1/1 [==============================] - 0s 2ms/step - loss: 0.1363 - accuracy: 1.0000
Epoch 984/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1361 - accuracy: 1.0000
Epoch 985/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1365 - accuracy: 1.0000
Epoch 986/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1361 - accuracy: 1.0000
Epoch 987/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1358 - accuracy: 1.0000
Epoch 988/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1360 - accuracy: 1.0000
Epoch 989/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1347 - accuracy: 1.0000
Epoch 990/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.1338 - accuracy: 1.0000
Epoch 991/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1338 - accuracy: 1.0000
Epoch 992/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1335 - accuracy: 1.0000
Epoch 993/1000


In [33]:
theta=my_mod.get_parameters()

AttributeError: 'Functional' object has no attribute 'get_parameters'

In [125]:
my_mod.predict([[1,1,1]])

array([[1.4844184e-05, 9.9998510e-01]], dtype=float32)